version: '3'
services:
  mongo:
    image: "mongo:3.4"
    command: mongod --port 27017
    ports:
      - "27017:27017"
    expose:
      - "27017"  
  api:
    # build: 
    #   context: https://github.com/chenweiLabri/WAT.git
    #   dockerfile: ./api/Dockerfile
    image: "wchen001/testscriptevolution_api"
    ports:
      - "8086:8086"      
    depends_on:      
      - "mongo"
            
volumes:
  screens:
